name: Deploy to EC2 on production branch push

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Archive build folder into tar
        run: tar -czf build.tar.gz -C dist .

      - name: Archive server folder into tar
        run: tar -czf server.tar.gz -C server .

      - name: Upload tar to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "build.tar.gz,server.tar.gz"
          target: "/home/ubuntu"

      - name: Extract and move files on EC2 with sudo
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            mkdir -p /home/ubuntu/datadump-temp
            tar -xzf /home/ubuntu/build.tar.gz -C /home/ubuntu/datadump-temp
            sudo rm -rf /var/www/datadump/*
            sudo mv /home/ubuntu/datadump-temp/* /var/www/datadump/
            rm -rf /home/ubuntu/build.tar.gz /home/ubuntu/datadump-temp
            # Deploy server
            mkdir -p /home/ubuntu/server-temp
            tar -xzf /home/ubuntu/server.tar.gz -C /home/ubuntu/server-temp
            sudo mkdir -p /var/www/h-data-server
            sudo rm -rf /var/www/h-data-server/*
            sudo mv /home/ubuntu/server-temp/* /var/www/h-data-server/
            rm -rf /home/ubuntu/server.tar.gz /home/ubuntu/server-temp
            # Install server dependencies and restart (adjust as needed)
            cd /var/www/h-data-server
            sudo npm install --omit=dev
            pm2 restart app || pm2 start app.js --name datadump
